### ISSUE TITLE
Missing MANIFEST.in

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq-plugins-public#50]
Most plug-ins have a MANIFEST.in referencing their stoq file(s)...
`include decompress/*.stoq`
...but these three omit it?:
- jinja
- peinfom
- yara

**Comment by serializingme** [comment]
There are two ways of doing it, one uses the `MANIFEST.in` file and the other specifies the files to include in `setup.py`.

**Comment by Kolano** [comment]
Hrm, OK, though the inconsistency may be a bit confusing.

**Comment by mlaferrera** [comment]
There are multiple ways of ensuring package data is placed in the correct location, all of which is documented in `setuptools`. I'm fine with it being done differently in the core plugins since one of the primary purposes of the plugins (aside from being functional) is to provide examples of how plugins can be written for those wishing to write their own. I would not consider it inconsistent in a negative way, but rather view it as providing examples for the multitude of ways one can write plugins.

To answer you question @Kolano, no, there is no real difference between the two from the perspective of stoQ plugins.
