### ISSUE TITLE
Better Handling of Excessively Large Compressed Files

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq-plugins-public#60]
The decompress maximum_size option is carefully worded (i.e. "to process")...

```
# Maximum size of payloads to process (original compressed file and extracted files)
# Default: 50MB
maximum_size = 50000000
```

No checks seem to be made with regards to file size before attempting extraction, so StoQ will attempt to extract archives with huge content (presuming the extraction doesn't exceed the timeout). A lot of data can be output on an SSD in 45s (20-90Gb) which could cause trouble.

It may be preferable to consider archive meta-data before extraction.

Related to #43, regarding capturing meta-data for archives.

**Comment by mlaferrera** [comment]
stoQ does check the file size of the original payload before attempting to extract, but it does not attempt to get the file size for each compressed object prior to being extracted. However, before stoQ processes each extracted object it will check the file size and not process it if larger than the defined `maximum_size`. 

Because this plugin is a wrapper for multiple extraction utilities, it has the same limitation as discussed in #43. We will have to see if there is a better way of handling large objects in compressed archives across multiple extraction utilities.

**Comment by mlaferrera** [comment]
Closed due to inactivity. Please feel free to reopen if needed.
