### ISSUE TITLE
Mimetype: 'mime' is not defined?

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq-plugins-public#73]
On Ubuntu 19.04 I'm seeing this error from the mimetype plugin...

"worker:failed to scan: File \"/home/pass/.stoq/plugins/mimetype/mimetype.py\", line 45, in scan ; NameError: name 'mime' is not defined"

Something seems to be in conflict with stoQ's mime handling, I'm not able to replicate the error with only stoQ and the mimetype plug-in installed; still trying to pin down what else being installed specifically results in the error.

**Comment by Kolano** [comment]
This seems to occur post installing the symhash plugin.

`stoq install --github stoq:symhash`

**Comment by mlaferrera** [comment]
Thanks @Kolano. It appears as though this is due to [symhash](https://github.com/threatstream/symhash/blob/master/requirements.txt#L1) using the outdated [filemagic](https://github.com/aliles/filemagic) instead of [python-magic](https://github.com/ahupp/python-magic). Normally I'd say we could do a PR in symhash to update it, but that project appears to be abandoned. I'll see if there is a better way of handling it. I'm open to suggestions if you have any.

**Comment by Kolano** [comment]
Thanks for the quick response as usual.

I don't have an alternative atm, but we should probably at least update the documentation on the symhash plugin to indicate that it's incompatible with the mimetype one in the meantime.

**Comment by Kolano** [comment]
And could we run symhash in a separate venv from stoq to allow for the differing versions of filemagic between them?

I'm guessing that may add some extra complexity to how plug-ins are deployed, but it would probably be a good idea since I'd have a feeling this won't be the last time stoQ will need to handle version mismatches between all the tools it utilizes.

**Comment by mlaferrera** [comment]
This is fixed in the v3 branch. Essentially the `mimetype` stoQ plugin is now a dependency for this plugin to run properly. The `mimetype` plugin is able to handle both magic libraries.
