### ISSUE TITLE
smtp example uses incompatible dirmon 

### ISSUE THREAD

**Issue by rfaircloth-splunk** [PUNCH-Cyber/stoq-plugins-public#81]
when using the latest dockerimage and the example in the smtp plugin the following error is produced  
[2019-12-24 18:00:32,918 WARNING] stoq: Plugin dirmon not compatible with this version of stoQ. Unpredictable results may occur!

**Comment by mlaferrera** [comment]
Thanks, @rfaircloth-splunk . I assume you are using v3 of stoq? This is actually a bit misleading. It's due to stoq v3 being in beta, but the plugin states the min required version is v3 final. I'll try to clean that up in the framework to account for beta versions. The message is just a warning. The plugin should run normally.
